package com.spring.restful.shipments.app.common;

public interface DbQueries {
		String INSERT_SHIPMENT="INSERT INTO SHIPMENT (ID,NAME,SRCLOC,DESTLOC,STATUS,DESCRIPTION,CRATEDATE,LASTMODIFIED)VALUES(SHIPMENT_SEQ_ID.NEXTVAL,?,?,?,?,?,?,?)";
		String GET_ALL_SHIPMENT="SELECT ID, NAME, SRCLOC, DESTLOC, STATUS, DESCRIPTION, CRATEDATE, LASTMODIFIED FROM SHIPMENT";
		String GET_SHIPMENT_BY_ID= "SELECT ID, NAME, SRCLOC, DESTLOC, STATUS, DESCRIPTION, CRATEDATE, LASTMODIFIED FROM SHIPMENT WHERE ID =?";
		String UPDATE_SHIPMENT_BY_ID="UPDATE SHIPMENT SET NAME =?, SRCLOC =?, DESTLOC =?, STATUS =?, DESCRIPTION =?, LASTMODIFIED =? WHERE  ID =?"; 
		String DELETE_SHIPMENT_BY_ID="DELETE FROM SHIPMENT WHERE ID =?";
}
